// <auto-generated />
using System;
using APIhackArtilect;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace APIhackArtilect.Migrations
{
    [DbContext(typeof(ArtilectDbContext))]
    partial class ArtilectDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("APIhackArtilect.Members", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("DreamProject")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("InterestId")
                        .HasColumnType("int");

                    b.Property<string>("Mail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SkillId")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("InterestId");

                    b.HasIndex("SkillId");

                    b.ToTable("Members");
                });

            modelBuilder.Entity("APIhackArtilect.Model.Domain", b =>
                {
                    b.Property<int>("DomainId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DomainId");

                    b.ToTable("Domains");
                });

            modelBuilder.Entity("APIhackArtilect.Model.Friends", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("FriendFirstId")
                        .HasColumnType("int");

                    b.Property<int?>("FriendsSecondId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FriendFirstId");

                    b.HasIndex("FriendsSecondId");

                    b.ToTable("Friends");
                });

            modelBuilder.Entity("APIhackArtilect.Model.Interests", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<bool>("Architecture")
                        .HasColumnType("bit");

                    b.Property<bool>("Biologie")
                        .HasColumnType("bit");

                    b.Property<bool>("Couture")
                        .HasColumnType("bit");

                    b.Property<bool>("Design")
                        .HasColumnType("bit");

                    b.Property<bool>("Drone")
                        .HasColumnType("bit");

                    b.Property<bool>("Electronique")
                        .HasColumnType("bit");

                    b.Property<bool>("Machines")
                        .HasColumnType("bit");

                    b.Property<bool>("Media")
                        .HasColumnType("bit");

                    b.Property<bool>("Musique")
                        .HasColumnType("bit");

                    b.Property<bool>("Robotique")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Interests");
                });

            modelBuilder.Entity("APIhackArtilect.Model.Invitation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProjectId")
                        .HasColumnType("int");

                    b.Property<int?>("ReceiverId")
                        .HasColumnType("int");

                    b.Property<int?>("SenderId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("ReceiverId");

                    b.HasIndex("SenderId");

                    b.ToTable("Invitations");
                });

            modelBuilder.Entity("APIhackArtilect.Model.Skills", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<bool>("Architecture")
                        .HasColumnType("bit");

                    b.Property<bool>("Biologie")
                        .HasColumnType("bit");

                    b.Property<bool>("Couture")
                        .HasColumnType("bit");

                    b.Property<bool>("Design")
                        .HasColumnType("bit");

                    b.Property<bool>("Drone")
                        .HasColumnType("bit");

                    b.Property<bool>("Electronique")
                        .HasColumnType("bit");

                    b.Property<bool>("Machines")
                        .HasColumnType("bit");

                    b.Property<bool>("Media")
                        .HasColumnType("bit");

                    b.Property<bool>("Musique")
                        .HasColumnType("bit");

                    b.Property<bool>("Robotique")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Skills");
                });

            modelBuilder.Entity("APIhackArtilect.Model.Subscribe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProjectTargetId")
                        .HasColumnType("int");

                    b.Property<int?>("SenderId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProjectTargetId");

                    b.HasIndex("SenderId");

                    b.ToTable("Subcriptions");
                });

            modelBuilder.Entity("APIhackArtilect.Projects", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<bool>("Category")
                        .HasColumnType("bit");

                    b.Property<string>("DateBegin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DateEnd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SkillId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SkillId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("MembersProjects", b =>
                {
                    b.Property<int>("MembersListId")
                        .HasColumnType("int");

                    b.Property<int>("ProjectsListId")
                        .HasColumnType("int");

                    b.HasKey("MembersListId", "ProjectsListId");

                    b.HasIndex("ProjectsListId");

                    b.ToTable("MembersProjects");
                });

            modelBuilder.Entity("APIhackArtilect.Members", b =>
                {
                    b.HasOne("APIhackArtilect.Model.Interests", "Interest")
                        .WithMany()
                        .HasForeignKey("InterestId");

                    b.HasOne("APIhackArtilect.Model.Skills", "Skill")
                        .WithMany()
                        .HasForeignKey("SkillId");

                    b.Navigation("Interest");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("APIhackArtilect.Model.Friends", b =>
                {
                    b.HasOne("APIhackArtilect.Members", "FriendFirst")
                        .WithMany()
                        .HasForeignKey("FriendFirstId");

                    b.HasOne("APIhackArtilect.Members", "FriendsSecond")
                        .WithMany()
                        .HasForeignKey("FriendsSecondId");

                    b.Navigation("FriendFirst");

                    b.Navigation("FriendsSecond");
                });

            modelBuilder.Entity("APIhackArtilect.Model.Invitation", b =>
                {
                    b.HasOne("APIhackArtilect.Projects", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId");

                    b.HasOne("APIhackArtilect.Members", "Receiver")
                        .WithMany()
                        .HasForeignKey("ReceiverId");

                    b.HasOne("APIhackArtilect.Members", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId");

                    b.Navigation("Project");

                    b.Navigation("Receiver");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("APIhackArtilect.Model.Subscribe", b =>
                {
                    b.HasOne("APIhackArtilect.Projects", "ProjectTarget")
                        .WithMany()
                        .HasForeignKey("ProjectTargetId");

                    b.HasOne("APIhackArtilect.Members", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId");

                    b.Navigation("ProjectTarget");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("APIhackArtilect.Projects", b =>
                {
                    b.HasOne("APIhackArtilect.Model.Skills", "Skill")
                        .WithMany()
                        .HasForeignKey("SkillId");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("MembersProjects", b =>
                {
                    b.HasOne("APIhackArtilect.Members", null)
                        .WithMany()
                        .HasForeignKey("MembersListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("APIhackArtilect.Projects", null)
                        .WithMany()
                        .HasForeignKey("ProjectsListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
